// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1740023541);
user_pref("browser.search.region", "IN");
user_pref("calendar.caldav.googleResync", 1740023540);
user_pref("calendar.list.sortOrder", "fb1371fc-e5c9-48ec-9baa-417292d82ced");
user_pref("calendar.registry.fb1371fc-e5c9-48ec-9baa-417292d82ced.calendar-main-default", true);
user_pref("calendar.registry.fb1371fc-e5c9-48ec-9baa-417292d82ced.calendar-main-in-composite", true);
user_pref("calendar.registry.fb1371fc-e5c9-48ec-9baa-417292d82ced.disabled", true);
user_pref("calendar.registry.fb1371fc-e5c9-48ec-9baa-417292d82ced.name", "Home");
user_pref("calendar.registry.fb1371fc-e5c9-48ec-9baa-417292d82ced.type", "storage");
user_pref("calendar.registry.fb1371fc-e5c9-48ec-9baa-417292d82ced.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1743738575);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241211204238");
user_pref("extensions.lastAppVersion", "115.18.0");
user_pref("extensions.lastPlatformVersion", "115.18.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"b31776ee-e2a2-44ed-be79-0e52e0d445c1\",\"google@search.mozilla.org\":\"e92ec4ce-ed69-4458-8628-0ac0c04e3285\",\"ddg@search.mozilla.org\":\"c2b1a55b-4b2f-44a1-86ef-8af94e495424\",\"amazondotcom@search.mozilla.org\":\"f7f30b2d-2c68-4b7d-a6b6-3f3cd49776fe\",\"wikipedia@search.mozilla.org\":\"4a12d011-8caa-4fa2-9b96-437b822ec2a7\",\"bing@search.mozilla.org\":\"b9cb47bc-368e-41e3-8401-b2511a63bb77\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "ca17f6a6-adc7-4983-8adb-0bb651d7703");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.18.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1743738574);
user_pref("toolkit.telemetry.cachedClientID", "3118b339-746a-45d3-a8fe-714627c2c50b");
user_pref("toolkit.telemetry.previousBuildID", "20241211204238");
